// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgpeybJC8tYTpjIkU_5JJgTIaVNBwZKj8',
    appId: '1:1035477081562:web:6252eb3844c2ead6c874e3',
    messagingSenderId: '1035477081562',
    projectId: 'parking-assistant-3e6cd',
    authDomain: 'parking-assistant-3e6cd.firebaseapp.com',
    storageBucket: 'parking-assistant-3e6cd.firebasestorage.app',
    measurementId: 'G-2WZ8K3X5Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2GYDwtiquawuB21oltYCPsq-4zMTtMw',
    appId: '1:1035477081562:android:c304d76733ee1180c874e3',
    messagingSenderId: '1035477081562',
    projectId: 'parking-assistant-3e6cd',
    storageBucket: 'parking-assistant-3e6cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCDrcWDs-7xAWMalmFXUlXgdhsMo-4T_s',
    appId: '1:1035477081562:ios:6299b6a4d033015bc874e3',
    messagingSenderId: '1035477081562',
    projectId: 'parking-assistant-3e6cd',
    storageBucket: 'parking-assistant-3e6cd.firebasestorage.app',
    iosBundleId: 'com.example.parkingAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCDrcWDs-7xAWMalmFXUlXgdhsMo-4T_s',
    appId: '1:1035477081562:ios:6299b6a4d033015bc874e3',
    messagingSenderId: '1035477081562',
    projectId: 'parking-assistant-3e6cd',
    storageBucket: 'parking-assistant-3e6cd.firebasestorage.app',
    iosBundleId: 'com.example.parkingAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgpeybJC8tYTpjIkU_5JJgTIaVNBwZKj8',
    appId: '1:1035477081562:web:6066c4b66ebfd945c874e3',
    messagingSenderId: '1035477081562',
    projectId: 'parking-assistant-3e6cd',
    authDomain: 'parking-assistant-3e6cd.firebaseapp.com',
    storageBucket: 'parking-assistant-3e6cd.firebasestorage.app',
    measurementId: 'G-Q9VY41CYFH',
  );
}
